// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfjqaJ31u2fctXgOy7F4wJd-mDMFw2w48',
    appId: '1:831346640256:android:29909d01ca78555e7f6d65',
    messagingSenderId: '831346640256',
    projectId: 'alquimia-literaria-2c5d2',
    authDomain: 'alquimia-literaria-2c5d2.firebaseapp.com',
    databaseURL: 'https://alquimia-literaria-2c5d2-default-rtdb.firebaseio.com/',
    storageBucket: 'alquimia-literaria-2c5d2.firebasestorage.app',
    measurementId: 'G-EDGDBYQJK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfjqaJ31u2fctXgOy7F4wJd-mDMFw2w48',
    appId: '1:831346640256:android:119bb496a246afe87f6d65',
    messagingSenderId: '831346640256',
    projectId: 'alquimia-literaria-2c5d2',
    databaseURL: 'https://alquimia-literaria-2c5d2-default-rtdb.firebaseio.com',
    storageBucket: 'alquimia-literaria-2c5d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq9OL4RIJdm8as_ds5bB1JZWpmqJXTvB8',
    appId: '1:831346640256:ios:063f69394665cd7d7f6d65',
    messagingSenderId: '831346640256',
    projectId: 'alquimia-literaria-2c5d2',
    databaseURL: 'https://alquimia-literaria-2c5d2-default-rtdb.firebaseio.com',
    storageBucket: 'alquimia-literaria-2c5d2.firebasestorage.app',
    iosClientId: '831346640256-ufqnl669k7gnelg5le9p81mbtq00jlet.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookClubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq9OL4RIJdm8as_ds5bB1JZWpmqJXTvB8',
    appId: '1:831346640256:ios:063f69394665cd7d7f6d65',
    messagingSenderId: '831346640256',
    projectId: 'alquimia-literaria-2c5d2',
    databaseURL: 'https://alquimia-literaria-2c5d2-default-rtdb.firebaseio.com',
    storageBucket: 'alquimia-literaria-2c5d2.firebasestorage.app',
    iosClientId: '831346640256-ufqnl669k7gnelg5le9p81mbtq00jlet.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookClubApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXwXVqLDPWSG1w2a8ok1eLAtlafk-GGfQ',
    appId: '1:831346640256:web:d41e3325374469787f6d65',
    messagingSenderId: '831346640256',
    projectId: 'alquimia-literaria-2c5d2',
    authDomain: 'alquimia-literaria-2c5d2.firebaseapp.com',
    databaseURL: 'https://alquimia-literaria-2c5d2-default-rtdb.firebaseio.com',
    storageBucket: 'alquimia-literaria-2c5d2.firebasestorage.app',
    measurementId: 'G-4G7Y9H75RG',
  );
}
